-- =========================================================
-- BELLATEN — CUPONS DE DESCONTO
-- Execute uma vez no Supabase > SQL Editor
-- Compatível com products.id BIGINT
-- =========================================================

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  description text not null default '',
  discount_type text not null
    check (discount_type in ('percent', 'fixed')),
  discount_value numeric(12,2) not null
    check (discount_value > 0),
  min_order numeric(12,2) not null default 0
    check (min_order >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  usage_limit integer
    check (usage_limit is null or usage_limit > 0),
  usage_count integer not null default 0
    check (usage_count >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    discount_type <> 'percent'
    or discount_value <= 100
  ),
  check (
    ends_at is null
    or starts_at is null
    or ends_at > starts_at
  )
);

alter table public.orders
add column if not exists subtotal numeric(12,2) not null default 0;

alter table public.orders
add column if not exists discount numeric(12,2) not null default 0;

alter table public.orders
add column if not exists coupon_code text;

update public.orders
set subtotal = total
where subtotal = 0 and total > 0;

alter table public.coupons enable row level security;

drop policy if exists "Public can read active coupons" on public.coupons;
create policy "Public can read active coupons"
on public.coupons
for select
to anon, authenticated
using (active = true or auth.role() = 'authenticated');

drop policy if exists "Authenticated can insert coupons" on public.coupons;
create policy "Authenticated can insert coupons"
on public.coupons
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can update coupons" on public.coupons;
create policy "Authenticated can update coupons"
on public.coupons
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete coupons" on public.coupons;
create policy "Authenticated can delete coupons"
on public.coupons
for delete
to authenticated
using (true);

grant select on public.coupons to anon, authenticated;
grant insert, update, delete on public.coupons to authenticated;
grant usage, select on sequence public.coupons_id_seq to authenticated;

create or replace function public.validate_coupon(
  coupon_code_input text,
  cart_total_input numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  coupon_record public.coupons%rowtype;
  normalized_code text;
  discount_amount numeric(12,2);
begin
  normalized_code := upper(trim(coalesce(coupon_code_input, '')));

  if normalized_code = '' then
    raise exception 'Informe o código do cupom.';
  end if;

  select *
    into coupon_record
    from public.coupons
   where upper(code) = normalized_code;

  if not found then
    raise exception 'Cupom não encontrado.';
  end if;

  if coupon_record.active = false then
    raise exception 'Este cupom está inativo.';
  end if;

  if coupon_record.starts_at is not null
     and now() < coupon_record.starts_at then
    raise exception 'Este cupom ainda não está disponível.';
  end if;

  if coupon_record.ends_at is not null
     and now() > coupon_record.ends_at then
    raise exception 'Este cupom expirou.';
  end if;

  if coupon_record.usage_limit is not null
     and coupon_record.usage_count >= coupon_record.usage_limit then
    raise exception 'O limite de utilizações deste cupom foi atingido.';
  end if;

  if coalesce(cart_total_input, 0) < coupon_record.min_order then
    raise exception
      'Pedido mínimo para este cupom: %.',
      to_char(coupon_record.min_order, 'FM999999990D00');
  end if;

  if coupon_record.discount_type = 'percent' then
    discount_amount :=
      round(
        coalesce(cart_total_input, 0)
        * coupon_record.discount_value
        / 100,
        2
      );
  else
    discount_amount := coupon_record.discount_value;
  end if;

  discount_amount := least(
    discount_amount,
    coalesce(cart_total_input, 0)
  );

  return jsonb_build_object(
    'id', coupon_record.id,
    'code', coupon_record.code,
    'description', coupon_record.description,
    'discount_type', coupon_record.discount_type,
    'discount_value', coupon_record.discount_value,
    'discount', discount_amount,
    'total', greatest(coalesce(cart_total_input, 0) - discount_amount, 0)
  );
end;
$$;

grant execute on function public.validate_coupon(text, numeric)
to anon, authenticated;

create or replace function public.create_order(order_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  product_record public.products%rowtype;
  requested_quantity integer;
  product_id_value bigint;
  calculated_subtotal numeric(12,2) := 0;
  calculated_discount numeric(12,2) := 0;
  calculated_total numeric(12,2) := 0;
  normalized_coupon_code text;
  coupon_result jsonb;
  coupon_id_value bigint;
  new_order public.orders%rowtype;
begin
  if coalesce(trim(order_payload->>'customer_name'), '') = '' then
    raise exception 'Informe o nome do cliente.';
  end if;

  if coalesce(trim(order_payload->>'phone'), '') = '' then
    raise exception 'Informe o WhatsApp do cliente.';
  end if;

  if jsonb_typeof(order_payload->'items') <> 'array'
     or jsonb_array_length(order_payload->'items') = 0 then
    raise exception 'O carrinho está vazio.';
  end if;

  for item in
    select value
    from jsonb_array_elements(order_payload->'items')
  loop
    requested_quantity := greatest(
      coalesce((item->>'quantity')::integer, 1),
      1
    );

    product_id_value := (item->>'product_id')::bigint;

    select *
      into product_record
      from public.products
     where id = product_id_value
     for update;

    if not found then
      raise exception 'Produto não encontrado: %', item->>'name';
    end if;

    if coalesce(product_record.active, true) = false then
      raise exception 'Produto indisponível: %', product_record.name;
    end if;

    if coalesce(product_record.stock, 0) < requested_quantity then
      raise exception
        'Estoque insuficiente para %. Disponível: %.',
        product_record.name,
        product_record.stock;
    end if;

    calculated_subtotal :=
      calculated_subtotal +
      (coalesce(product_record.price, 0) * requested_quantity);
  end loop;

  normalized_coupon_code :=
    upper(trim(coalesce(order_payload->>'coupon_code', '')));

  if normalized_coupon_code <> '' then
    coupon_result := public.validate_coupon(
      normalized_coupon_code,
      calculated_subtotal
    );

    calculated_discount :=
      coalesce((coupon_result->>'discount')::numeric, 0);
    coupon_id_value :=
      (coupon_result->>'id')::bigint;
  end if;

  calculated_total :=
    greatest(calculated_subtotal - calculated_discount, 0);

  -- A baixa ocorre somente depois que todas as validações passaram.
  for item in
    select value
    from jsonb_array_elements(order_payload->'items')
  loop
    requested_quantity := greatest(
      coalesce((item->>'quantity')::integer, 1),
      1
    );
    product_id_value := (item->>'product_id')::bigint;

    update public.products
       set stock = stock - requested_quantity
     where id = product_id_value;
  end loop;

  if coupon_id_value is not null then
    update public.coupons
       set usage_count = usage_count + 1,
           updated_at = now()
     where id = coupon_id_value;
  end if;

  insert into public.orders (
    customer_name,
    phone,
    email,
    delivery_type,
    address,
    payment_method,
    notes,
    items,
    subtotal,
    discount,
    coupon_code,
    total,
    status
  )
  values (
    trim(order_payload->>'customer_name'),
    trim(order_payload->>'phone'),
    nullif(trim(order_payload->>'email'), ''),
    coalesce(nullif(order_payload->>'delivery_type', ''), 'retirada'),
    nullif(trim(order_payload->>'address'), ''),
    coalesce(nullif(order_payload->>'payment_method', ''), 'pix'),
    nullif(trim(order_payload->>'notes'), ''),
    order_payload->'items',
    calculated_subtotal,
    calculated_discount,
    nullif(normalized_coupon_code, ''),
    calculated_total,
    'recebido'
  )
  returning * into new_order;

  return jsonb_build_object(
    'id', new_order.id,
    'order_number', new_order.order_number,
    'subtotal', new_order.subtotal,
    'discount', new_order.discount,
    'coupon_code', new_order.coupon_code,
    'total', new_order.total,
    'status', new_order.status
  );
end;
$$;

grant execute on function public.create_order(jsonb)
to anon, authenticated;
