-- Execute este arquivo no Supabase: SQL Editor > New query > Run

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Maquiagem',
  price numeric(10,2) not null default 0 check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  image text not null default '',
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "Produtos visiveis publicamente" on public.products;
create policy "Produtos visiveis publicamente"
on public.products for select
to anon, authenticated
using (active = true or auth.role() = 'authenticated');

drop policy if exists "Administradores inserem produtos" on public.products;
create policy "Administradores inserem produtos"
on public.products for insert
to authenticated
with check (true);

drop policy if exists "Administradores atualizam produtos" on public.products;
create policy "Administradores atualizam produtos"
on public.products for update
to authenticated
using (true)
with check (true);

drop policy if exists "Administradores excluem produtos" on public.products;
create policy "Administradores excluem produtos"
on public.products for delete
to authenticated
using (true);

insert into storage.buckets (id, name, public)
values ('products', 'products', true)
on conflict (id) do update set public = true;

drop policy if exists "Imagens publicas" on storage.objects;
create policy "Imagens publicas"
on storage.objects for select
to public
using (bucket_id = 'products');

drop policy if exists "Admin envia imagens" on storage.objects;
create policy "Admin envia imagens"
on storage.objects for insert
to authenticated
with check (bucket_id = 'products');

drop policy if exists "Admin atualiza imagens" on storage.objects;
create policy "Admin atualiza imagens"
on storage.objects for update
to authenticated
using (bucket_id = 'products')
with check (bucket_id = 'products');

drop policy if exists "Admin exclui imagens" on storage.objects;
create policy "Admin exclui imagens"
on storage.objects for delete
to authenticated
using (bucket_id = 'products');

-- Categorias administráveis
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  image text not null default '',
  active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.categories enable row level security;
grant select on table public.categories to anon, authenticated;
grant insert, update, delete on table public.categories to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Categorias visiveis publicamente" on public.categories;
create policy "Categorias visiveis publicamente"
on public.categories for select
to anon, authenticated
using (active = true or auth.role() = 'authenticated');

drop policy if exists "Administradores inserem categorias" on public.categories;
create policy "Administradores inserem categorias"
on public.categories for insert
to authenticated
with check (true);

drop policy if exists "Administradores atualizam categorias" on public.categories;
create policy "Administradores atualizam categorias"
on public.categories for update
to authenticated
using (true)
with check (true);

drop policy if exists "Administradores excluem categorias" on public.categories;
create policy "Administradores excluem categorias"
on public.categories for delete
to authenticated
using (true);

insert into public.categories (name, image, active, display_order)
values
  ('Maquiagem', 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=500&q=80', true, 1),
  ('Skincare', 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=500&q=80', true, 2),
  ('Cabelos', 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=500&q=80', true, 3),
  ('Corpo e Banho', 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=500&q=80', true, 4),
  ('Acessórios', 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=500&q=80', true, 5)
on conflict (name) do nothing;
