-- =========================================================
-- BELLATEN — PEDIDOS + BAIXA AUTOMÁTICA DE ESTOQUE
-- Execute uma vez no Supabase > SQL Editor
-- =========================================================

create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity,
  customer_name text not null,
  phone text not null,
  email text,
  delivery_type text not null default 'retirada',
  address text,
  payment_method text not null default 'pix',
  notes text,
  items jsonb not null default '[]'::jsonb,
  total numeric(12,2) not null default 0,
  status text not null default 'recebido',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders add column if not exists customer_name text;
alter table public.orders add column if not exists phone text;
alter table public.orders add column if not exists email text;
alter table public.orders add column if not exists delivery_type text default 'retirada';
alter table public.orders add column if not exists address text;
alter table public.orders add column if not exists payment_method text default 'pix';
alter table public.orders add column if not exists notes text;
alter table public.orders add column if not exists items jsonb default '[]'::jsonb;
alter table public.orders add column if not exists total numeric(12,2) default 0;
alter table public.orders add column if not exists status text default 'recebido';
alter table public.orders add column if not exists created_at timestamptz default now();
alter table public.orders add column if not exists updated_at timestamptz default now();

update public.orders
set status = case
  when status = 'novo' then 'recebido'
  when status = 'atendimento' then 'separacao'
  else status
end
where status in ('novo', 'atendimento');

create or replace function public.create_order(order_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  product_record public.products%rowtype;
  requested_quantity integer;
  calculated_total numeric(12,2) := 0;
  new_order public.orders%rowtype;
begin
  if coalesce(trim(order_payload->>'customer_name'), '') = '' then
    raise exception 'Informe o nome do cliente.';
  end if;

  if coalesce(trim(order_payload->>'phone'), '') = '' then
    raise exception 'Informe o WhatsApp do cliente.';
  end if;

  if jsonb_typeof(order_payload->'items') <> 'array'
     or jsonb_array_length(order_payload->'items') = 0 then
    raise exception 'O carrinho está vazio.';
  end if;

  for item in
    select value from jsonb_array_elements(order_payload->'items')
  loop
    requested_quantity := greatest((item->>'quantity')::integer, 1);

    select *
      into product_record
      from public.products
     where id = (item->>'product_id')::uuid
     for update;

    if not found then
      raise exception 'Produto não encontrado: %', item->>'name';
    end if;

    if coalesce(product_record.active, true) = false then
      raise exception 'Produto indisponível: %', product_record.name;
    end if;

    if coalesce(product_record.stock, 0) < requested_quantity then
      raise exception
        'Estoque insuficiente para %. Disponível: %.',
        product_record.name,
        product_record.stock;
    end if;

    calculated_total :=
      calculated_total +
      (coalesce(product_record.price, 0) * requested_quantity);

    update public.products
       set stock = stock - requested_quantity
     where id = product_record.id;
  end loop;

  insert into public.orders (
    customer_name,
    phone,
    email,
    delivery_type,
    address,
    payment_method,
    notes,
    items,
    total,
    status
  )
  values (
    trim(order_payload->>'customer_name'),
    trim(order_payload->>'phone'),
    nullif(trim(order_payload->>'email'), ''),
    coalesce(nullif(order_payload->>'delivery_type', ''), 'retirada'),
    nullif(trim(order_payload->>'address'), ''),
    coalesce(nullif(order_payload->>'payment_method', ''), 'pix'),
    nullif(trim(order_payload->>'notes'), ''),
    order_payload->'items',
    calculated_total,
    'recebido'
  )
  returning * into new_order;

  return jsonb_build_object(
    'id', new_order.id,
    'order_number', new_order.order_number,
    'total', new_order.total,
    'status', new_order.status
  );
end;
$$;

grant execute on function public.create_order(jsonb) to anon, authenticated;

alter table public.orders enable row level security;

drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders"
on public.orders
for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated can read orders" on public.orders;
create policy "Authenticated can read orders"
on public.orders
for select
to authenticated
using (true);

drop policy if exists "Authenticated can update orders" on public.orders;
create policy "Authenticated can update orders"
on public.orders
for update
to authenticated
using (true)
with check (true);
