-- =========================================================
-- BELLATEN — MOVIMENTAÇÕES DE ESTOQUE
-- Execute uma vez no Supabase > SQL Editor
-- Compatível com products.id BIGINT
-- =========================================================

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  product_name text not null,
  movement_type text not null
    check (movement_type in ('entrada', 'saida', 'venda')),
  quantity integer not null,
  stock_before integer not null,
  stock_after integer not null,
  reason text not null default '',
  order_id uuid,
  created_by uuid,
  created_at timestamptz not null default now()
);

create index if not exists stock_movements_product_id_idx
on public.stock_movements(product_id);

create index if not exists stock_movements_created_at_idx
on public.stock_movements(created_at desc);

alter table public.stock_movements enable row level security;

drop policy if exists "Authenticated can read stock movements"
on public.stock_movements;

create policy "Authenticated can read stock movements"
on public.stock_movements
for select
to authenticated
using (true);

grant select on public.stock_movements to authenticated;
grant usage, select on sequence public.stock_movements_id_seq to authenticated;

create or replace function public.adjust_product_stock(
  product_id_input bigint,
  movement_type_input text,
  quantity_input integer,
  reason_input text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  product_record public.products%rowtype;
  signed_quantity integer;
  new_stock integer;
begin
  if auth.uid() is null then
    raise exception 'Usuário não autenticado.';
  end if;

  if movement_type_input not in ('entrada', 'saida') then
    raise exception 'Tipo de movimentação inválido.';
  end if;

  if coalesce(quantity_input, 0) <= 0 then
    raise exception 'A quantidade deve ser maior que zero.';
  end if;

  if coalesce(trim(reason_input), '') = '' then
    raise exception 'Informe o motivo do ajuste.';
  end if;

  select *
    into product_record
    from public.products
   where id = product_id_input
   for update;

  if not found then
    raise exception 'Produto não encontrado.';
  end if;

  signed_quantity :=
    case
      when movement_type_input = 'entrada' then quantity_input
      else -quantity_input
    end;

  new_stock := coalesce(product_record.stock, 0) + signed_quantity;

  if new_stock < 0 then
    raise exception
      'Estoque insuficiente. Quantidade atual: %.',
      product_record.stock;
  end if;

  update public.products
     set stock = new_stock
   where id = product_record.id;

  insert into public.stock_movements (
    product_id,
    product_name,
    movement_type,
    quantity,
    stock_before,
    stock_after,
    reason,
    created_by
  )
  values (
    product_record.id,
    product_record.name,
    movement_type_input,
    signed_quantity,
    product_record.stock,
    new_stock,
    trim(reason_input),
    auth.uid()
  );

  return jsonb_build_object(
    'product_id', product_record.id,
    'stock_before', product_record.stock,
    'stock_after', new_stock
  );
end;
$$;

grant execute on function public.adjust_product_stock(
  bigint,
  text,
  integer,
  text
) to authenticated;

-- Atualiza create_order para registrar cada venda no histórico.
create or replace function public.create_order(order_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  product_record public.products%rowtype;
  requested_quantity integer;
  product_id_value bigint;
  calculated_subtotal numeric(12,2) := 0;
  calculated_discount numeric(12,2) := 0;
  calculated_total numeric(12,2) := 0;
  normalized_coupon_code text;
  coupon_result jsonb;
  coupon_id_value bigint;
  new_order public.orders%rowtype;
  stock_before_value integer;
  stock_after_value integer;
begin
  if coalesce(trim(order_payload->>'customer_name'), '') = '' then
    raise exception 'Informe o nome do cliente.';
  end if;

  if coalesce(trim(order_payload->>'phone'), '') = '' then
    raise exception 'Informe o WhatsApp do cliente.';
  end if;

  if jsonb_typeof(order_payload->'items') <> 'array'
     or jsonb_array_length(order_payload->'items') = 0 then
    raise exception 'O carrinho está vazio.';
  end if;

  for item in
    select value
    from jsonb_array_elements(order_payload->'items')
  loop
    requested_quantity := greatest(
      coalesce((item->>'quantity')::integer, 1),
      1
    );

    product_id_value := (item->>'product_id')::bigint;

    select *
      into product_record
      from public.products
     where id = product_id_value
     for update;

    if not found then
      raise exception 'Produto não encontrado: %', item->>'name';
    end if;

    if coalesce(product_record.active, true) = false then
      raise exception 'Produto indisponível: %', product_record.name;
    end if;

    if coalesce(product_record.stock, 0) < requested_quantity then
      raise exception
        'Estoque insuficiente para %. Disponível: %.',
        product_record.name,
        product_record.stock;
    end if;

    calculated_subtotal :=
      calculated_subtotal +
      (coalesce(product_record.price, 0) * requested_quantity);
  end loop;

  normalized_coupon_code :=
    upper(trim(coalesce(order_payload->>'coupon_code', '')));

  if normalized_coupon_code <> '' then
    coupon_result := public.validate_coupon(
      normalized_coupon_code,
      calculated_subtotal
    );

    calculated_discount :=
      coalesce((coupon_result->>'discount')::numeric, 0);
    coupon_id_value :=
      (coupon_result->>'id')::bigint;
  end if;

  calculated_total :=
    greatest(calculated_subtotal - calculated_discount, 0);

  insert into public.orders (
    customer_name,
    phone,
    email,
    delivery_type,
    address,
    payment_method,
    notes,
    items,
    subtotal,
    discount,
    coupon_code,
    total,
    status,
    tracking_token
  )
  values (
    trim(order_payload->>'customer_name'),
    trim(order_payload->>'phone'),
    nullif(trim(order_payload->>'email'), ''),
    coalesce(nullif(order_payload->>'delivery_type', ''), 'retirada'),
    nullif(trim(order_payload->>'address'), ''),
    coalesce(nullif(order_payload->>'payment_method', ''), 'pix'),
    nullif(trim(order_payload->>'notes'), ''),
    order_payload->'items',
    calculated_subtotal,
    calculated_discount,
    nullif(normalized_coupon_code, ''),
    calculated_total,
    'recebido',
    gen_random_uuid()
  )
  returning * into new_order;

  for item in
    select value
    from jsonb_array_elements(order_payload->'items')
  loop
    requested_quantity := greatest(
      coalesce((item->>'quantity')::integer, 1),
      1
    );
    product_id_value := (item->>'product_id')::bigint;

    select *
      into product_record
      from public.products
     where id = product_id_value
     for update;

    stock_before_value := product_record.stock;
    stock_after_value := stock_before_value - requested_quantity;

    update public.products
       set stock = stock_after_value
     where id = product_id_value;

    insert into public.stock_movements (
      product_id,
      product_name,
      movement_type,
      quantity,
      stock_before,
      stock_after,
      reason,
      order_id
    )
    values (
      product_record.id,
      product_record.name,
      'venda',
      -requested_quantity,
      stock_before_value,
      stock_after_value,
      'Venda do pedido #' || new_order.order_number,
      new_order.id
    );
  end loop;

  if coupon_id_value is not null then
    update public.coupons
       set usage_count = usage_count + 1,
           updated_at = now()
     where id = coupon_id_value;
  end if;

  return jsonb_build_object(
    'id', new_order.id,
    'order_number', new_order.order_number,
    'subtotal', new_order.subtotal,
    'discount', new_order.discount,
    'coupon_code', new_order.coupon_code,
    'total', new_order.total,
    'status', new_order.status,
    'tracking_token', new_order.tracking_token
  );
end;
$$;

grant execute on function public.create_order(jsonb)
to anon, authenticated;
